-- Удаляем таблицы если существуют
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS genres;

-- Создаем таблицы
CREATE TABLE authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    birth_year INT,
    country VARCHAR(100),
    biography VARCHAR(1000)
);

CREATE TABLE genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500)
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    publication_year INT NOT NULL,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    pages INT,
    quantity INT DEFAULT 0,
    description VARCHAR(1000),
    FOREIGN KEY (author_id) REFERENCES authors(id),
    FOREIGN KEY (genre_id) REFERENCES genres(id)
);

-- Вставляем тестовые данные
INSERT INTO authors (first_name, last_name, birth_year, country) VALUES
('Лев', 'Толстой', 1828, 'Россия'),
('Федор', 'Достоевский', 1821, 'Россия'),
('Александр', 'Пушкин', 1799, 'Россия'),
('Антон', 'Чехов', 1860, 'Россия'),
('Михаил', 'Булгаков', 1891, 'Россия');

INSERT INTO genres (name, description) VALUES
('Роман', 'Художественное произведение большого объема'),
('Поэзия', 'Стихотворные произведения'),
('Драма', 'Драматические произведения'),
('Фантастика', 'Научная фантастика и фэнтези'),
('Детектив', 'Детективные произведения');

INSERT INTO books (title, author_id, genre_id, publication_year, isbn, pages, quantity) VALUES
('Война и мир', 1, 1, 1869, '978-5-17-090021-5', 1225, 10),
('Преступление и наказание', 2, 1, 1866, '978-5-17-090021-6', 672, 8),
('Евгений Онегин', 3, 2, 1833, '978-5-17-090021-7', 320, 15),
('Вишневый сад', 4, 3, 1904, '978-5-17-090021-8', 96, 12),
('Мастер и Маргарита', 5, 4, 1967, '978-5-17-090021-9', 480, 20);